/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "Empty.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace OpenAPI {

Empty::Empty(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

Empty::Empty() {
    this->initializeModel();
}

Empty::~Empty() {}

void Empty::initializeModel() {

    m_tracking_id_isSet = false;
    m_tracking_id_isValid = false;

    m_payload_isSet = false;
    m_payload_isValid = false;

    m_status_isSet = false;
    m_status_isValid = false;
}

void Empty::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void Empty::fromJsonObject(QJsonObject json) {

    m_tracking_id_isValid = ::OpenAPI::fromJsonValue(tracking_id, json[QString("trackingId")]);
    m_tracking_id_isSet = !json[QString("trackingId")].isNull() && m_tracking_id_isValid;

    m_payload_isValid = ::OpenAPI::fromJsonValue(payload, json[QString("payload")]);
    m_payload_isSet = !json[QString("payload")].isNull() && m_payload_isValid;

    m_status_isValid = ::OpenAPI::fromJsonValue(status, json[QString("status")]);
    m_status_isSet = !json[QString("status")].isNull() && m_status_isValid;
}

QString Empty::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject Empty::asJsonObject() const {
    QJsonObject obj;
    if (m_tracking_id_isSet) {
        obj.insert(QString("trackingId"), ::OpenAPI::toJsonValue(tracking_id));
    }
    if (m_payload_isSet) {
        obj.insert(QString("payload"), ::OpenAPI::toJsonValue(payload));
    }
    if (m_status_isSet) {
        obj.insert(QString("status"), ::OpenAPI::toJsonValue(status));
    }
    return obj;
}

QString Empty::getTrackingId() const {
    return tracking_id;
}
void Empty::setTrackingId(const QString &tracking_id) {
    this->tracking_id = tracking_id;
    this->m_tracking_id_isSet = true;
}

bool Empty::is_tracking_id_Set() const{
    return m_tracking_id_isSet;
}

bool Empty::is_tracking_id_Valid() const{
    return m_tracking_id_isValid;
}

Object Empty::getPayload() const {
    return payload;
}
void Empty::setPayload(const Object &payload) {
    this->payload = payload;
    this->m_payload_isSet = true;
}

bool Empty::is_payload_Set() const{
    return m_payload_isSet;
}

bool Empty::is_payload_Valid() const{
    return m_payload_isValid;
}

QString Empty::getStatus() const {
    return status;
}
void Empty::setStatus(const QString &status) {
    this->status = status;
    this->m_status_isSet = true;
}

bool Empty::is_status_Set() const{
    return m_status_isSet;
}

bool Empty::is_status_Valid() const{
    return m_status_isValid;
}

bool Empty::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_tracking_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_payload_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_status_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool Empty::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_tracking_id_isValid && m_payload_isValid && m_status_isValid && true;
}

} // namespace OpenAPI
