/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "Error_payload.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace OpenAPI {

Error_payload::Error_payload(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

Error_payload::Error_payload() {
    this->initializeModel();
}

Error_payload::~Error_payload() {}

void Error_payload::initializeModel() {

    m_message_isSet = false;
    m_message_isValid = false;

    m_code_isSet = false;
    m_code_isValid = false;
}

void Error_payload::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void Error_payload::fromJsonObject(QJsonObject json) {

    m_message_isValid = ::OpenAPI::fromJsonValue(message, json[QString("message")]);
    m_message_isSet = !json[QString("message")].isNull() && m_message_isValid;

    m_code_isValid = ::OpenAPI::fromJsonValue(code, json[QString("code")]);
    m_code_isSet = !json[QString("code")].isNull() && m_code_isValid;
}

QString Error_payload::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject Error_payload::asJsonObject() const {
    QJsonObject obj;
    if (m_message_isSet) {
        obj.insert(QString("message"), ::OpenAPI::toJsonValue(message));
    }
    if (m_code_isSet) {
        obj.insert(QString("code"), ::OpenAPI::toJsonValue(code));
    }
    return obj;
}

QString Error_payload::getMessage() const {
    return message;
}
void Error_payload::setMessage(const QString &message) {
    this->message = message;
    this->m_message_isSet = true;
}

bool Error_payload::is_message_Set() const{
    return m_message_isSet;
}

bool Error_payload::is_message_Valid() const{
    return m_message_isValid;
}

QString Error_payload::getCode() const {
    return code;
}
void Error_payload::setCode(const QString &code) {
    this->code = code;
    this->m_code_isSet = true;
}

bool Error_payload::is_code_Set() const{
    return m_code_isSet;
}

bool Error_payload::is_code_Valid() const{
    return m_code_isValid;
}

bool Error_payload::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_message_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_code_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool Error_payload::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
