/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "LimitOrderRequest.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace OpenAPI {

LimitOrderRequest::LimitOrderRequest(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

LimitOrderRequest::LimitOrderRequest() {
    this->initializeModel();
}

LimitOrderRequest::~LimitOrderRequest() {}

void LimitOrderRequest::initializeModel() {

    m_lots_isSet = false;
    m_lots_isValid = false;

    m_operation_isSet = false;
    m_operation_isValid = false;

    m_price_isSet = false;
    m_price_isValid = false;
}

void LimitOrderRequest::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void LimitOrderRequest::fromJsonObject(QJsonObject json) {

    m_lots_isValid = ::OpenAPI::fromJsonValue(lots, json[QString("lots")]);
    m_lots_isSet = !json[QString("lots")].isNull() && m_lots_isValid;

    m_operation_isValid = ::OpenAPI::fromJsonValue(operation, json[QString("operation")]);
    m_operation_isSet = !json[QString("operation")].isNull() && m_operation_isValid;

    m_price_isValid = ::OpenAPI::fromJsonValue(price, json[QString("price")]);
    m_price_isSet = !json[QString("price")].isNull() && m_price_isValid;
}

QString LimitOrderRequest::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject LimitOrderRequest::asJsonObject() const {
    QJsonObject obj;
    if (m_lots_isSet) {
        obj.insert(QString("lots"), ::OpenAPI::toJsonValue(lots));
    }
    if (operation.isSet()) {
        obj.insert(QString("operation"), ::OpenAPI::toJsonValue(operation));
    }
    if (m_price_isSet) {
        obj.insert(QString("price"), ::OpenAPI::toJsonValue(price));
    }
    return obj;
}

qint32 LimitOrderRequest::getLots() const {
    return lots;
}
void LimitOrderRequest::setLots(const qint32 &lots) {
    this->lots = lots;
    this->m_lots_isSet = true;
}

bool LimitOrderRequest::is_lots_Set() const{
    return m_lots_isSet;
}

bool LimitOrderRequest::is_lots_Valid() const{
    return m_lots_isValid;
}

OperationType LimitOrderRequest::getOperation() const {
    return operation;
}
void LimitOrderRequest::setOperation(const OperationType &operation) {
    this->operation = operation;
    this->m_operation_isSet = true;
}

bool LimitOrderRequest::is_operation_Set() const{
    return m_operation_isSet;
}

bool LimitOrderRequest::is_operation_Valid() const{
    return m_operation_isValid;
}

double LimitOrderRequest::getPrice() const {
    return price;
}
void LimitOrderRequest::setPrice(const double &price) {
    this->price = price;
    this->m_price_isSet = true;
}

bool LimitOrderRequest::is_price_Set() const{
    return m_price_isSet;
}

bool LimitOrderRequest::is_price_Valid() const{
    return m_price_isValid;
}

bool LimitOrderRequest::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_lots_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (operation.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_price_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool LimitOrderRequest::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_lots_isValid && m_operation_isValid && m_price_isValid && true;
}

} // namespace OpenAPI
