/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef _MarketApi_H
#define _MarketApi_H

#include "HttpRequest.h"

#include "CandleResolution.h"
#include "CandlesResponse.h"
#include "Error.h"
#include "MarketInstrumentListResponse.h"
#include "OrderbookResponse.h"
#include "SearchMarketInstrumentResponse.h"
#include <QString>

#include <QObject>

namespace OpenAPI {

class MarketApi : public QObject {
    Q_OBJECT

public:
    MarketApi(const QString &scheme = "https", const QString &host = "api-invest.tinkoff.ru", int port = 0, const QString &basePath = "/openapi", const int timeOut = 0);
    ~MarketApi();

    void setScheme(const QString &scheme);
    void setHost(const QString &host);
    void setPort(int port);
    void setBasePath(const QString &basePath);
    void setTimeOut(const int timeOut);
    void setWorkingDirectory(const QString &path);
    void addHeaders(const QString &key, const QString &value);
    void enableRequestCompression();
    void enableResponseCompression();
    void abortRequests();

    void marketBondsGet();
    void marketCandlesGet(const QString &figi, const QDateTime &from, const QDateTime &to, const CandleResolution &interval);
    void marketCurrenciesGet();
    void marketEtfsGet();
    void marketOrderbookGet(const QString &figi, const qint32 &depth);
    void marketSearchByFigiGet(const QString &figi);
    void marketSearchByTickerGet(const QString &ticker);
    void marketStocksGet();

private:
    QString _scheme, _host;
    int _port;
    QString _basePath;
    int _timeOut;
    QString _workingDirectory;
    QMap<QString, QString> defaultHeaders;
    bool isResponseCompressionEnabled;
    bool isRequestCompressionEnabled;

    void marketBondsGetCallback(HttpRequestWorker *worker);
    void marketCandlesGetCallback(HttpRequestWorker *worker);
    void marketCurrenciesGetCallback(HttpRequestWorker *worker);
    void marketEtfsGetCallback(HttpRequestWorker *worker);
    void marketOrderbookGetCallback(HttpRequestWorker *worker);
    void marketSearchByFigiGetCallback(HttpRequestWorker *worker);
    void marketSearchByTickerGetCallback(HttpRequestWorker *worker);
    void marketStocksGetCallback(HttpRequestWorker *worker);

signals:

    void marketBondsGetSignal(MarketInstrumentListResponse summary);
    void marketCandlesGetSignal(CandlesResponse summary);
    void marketCurrenciesGetSignal(MarketInstrumentListResponse summary);
    void marketEtfsGetSignal(MarketInstrumentListResponse summary);
    void marketOrderbookGetSignal(OrderbookResponse summary);
    void marketSearchByFigiGetSignal(SearchMarketInstrumentResponse summary);
    void marketSearchByTickerGetSignal(MarketInstrumentListResponse summary);
    void marketStocksGetSignal(MarketInstrumentListResponse summary);

    void marketBondsGetSignalFull(HttpRequestWorker *worker, MarketInstrumentListResponse summary);
    void marketCandlesGetSignalFull(HttpRequestWorker *worker, CandlesResponse summary);
    void marketCurrenciesGetSignalFull(HttpRequestWorker *worker, MarketInstrumentListResponse summary);
    void marketEtfsGetSignalFull(HttpRequestWorker *worker, MarketInstrumentListResponse summary);
    void marketOrderbookGetSignalFull(HttpRequestWorker *worker, OrderbookResponse summary);
    void marketSearchByFigiGetSignalFull(HttpRequestWorker *worker, SearchMarketInstrumentResponse summary);
    void marketSearchByTickerGetSignalFull(HttpRequestWorker *worker, MarketInstrumentListResponse summary);
    void marketStocksGetSignalFull(HttpRequestWorker *worker, MarketInstrumentListResponse summary);

    void marketBondsGetSignalE(MarketInstrumentListResponse summary, QNetworkReply::NetworkError error_type, QString error_str);
    void marketCandlesGetSignalE(CandlesResponse summary, QNetworkReply::NetworkError error_type, QString error_str);
    void marketCurrenciesGetSignalE(MarketInstrumentListResponse summary, QNetworkReply::NetworkError error_type, QString error_str);
    void marketEtfsGetSignalE(MarketInstrumentListResponse summary, QNetworkReply::NetworkError error_type, QString error_str);
    void marketOrderbookGetSignalE(OrderbookResponse summary, QNetworkReply::NetworkError error_type, QString error_str);
    void marketSearchByFigiGetSignalE(SearchMarketInstrumentResponse summary, QNetworkReply::NetworkError error_type, QString error_str);
    void marketSearchByTickerGetSignalE(MarketInstrumentListResponse summary, QNetworkReply::NetworkError error_type, QString error_str);
    void marketStocksGetSignalE(MarketInstrumentListResponse summary, QNetworkReply::NetworkError error_type, QString error_str);

    void marketBondsGetSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void marketCandlesGetSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void marketCurrenciesGetSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void marketEtfsGetSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void marketOrderbookGetSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void marketSearchByFigiGetSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void marketSearchByTickerGetSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void marketStocksGetSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);

    void abortRequestsSignal(); 
};

} // namespace OpenAPI
#endif
