/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OperationStatus.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace OpenAPI {

OperationStatus::OperationStatus(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OperationStatus::OperationStatus() {
    this->initializeModel();
}

OperationStatus::~OperationStatus() {}

void OperationStatus::initializeModel() {

    m_value_isSet = false;
    m_value_isValid = false;
    m_value = eOperationStatus::INVALID_VALUE_OPENAPI_GENERATED;
}

void OperationStatus::fromJson(QString jsonString) {
    
    if ( jsonString.compare("Done", Qt::CaseInsensitive) == 0) {
        m_value = eOperationStatus::DONE;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Decline", Qt::CaseInsensitive) == 0) {
        m_value = eOperationStatus::DECLINE;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Progress", Qt::CaseInsensitive) == 0) {
        m_value = eOperationStatus::PROGRESS;
        m_value_isSet = m_value_isValid = true;
    }
}

void OperationStatus::fromJsonValue(QJsonValue json) {
fromJson(json.toString());
}

QString OperationStatus::asJson() const {
    
    QString val;
    switch (m_value){
        case eOperationStatus::DONE:
            val = "Done";
            break;
        case eOperationStatus::DECLINE:
            val = "Decline";
            break;
        case eOperationStatus::PROGRESS:
            val = "Progress";
            break;
        default:
            break;
    }
    return val;
}

QJsonValue OperationStatus::asJsonValue() const {
    
    return QJsonValue(asJson());
}


OperationStatus::eOperationStatus OperationStatus::getValue() const {
    return m_value;
}

void OperationStatus::setValue(const OperationStatus::eOperationStatus& value){
    m_value = value;
    m_value_isSet = true;
}
bool OperationStatus::isSet() const {
    
    return m_value_isSet;
}

bool OperationStatus::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_value_isValid;
}

} // namespace OpenAPI
