/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OperationTypeWithCommission.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace OpenAPI {

OperationTypeWithCommission::OperationTypeWithCommission(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OperationTypeWithCommission::OperationTypeWithCommission() {
    this->initializeModel();
}

OperationTypeWithCommission::~OperationTypeWithCommission() {}

void OperationTypeWithCommission::initializeModel() {

    m_value_isSet = false;
    m_value_isValid = false;
    m_value = eOperationTypeWithCommission::INVALID_VALUE_OPENAPI_GENERATED;
}

void OperationTypeWithCommission::fromJson(QString jsonString) {
    
    if ( jsonString.compare("Buy", Qt::CaseInsensitive) == 0) {
        m_value = eOperationTypeWithCommission::BUY;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("BuyCard", Qt::CaseInsensitive) == 0) {
        m_value = eOperationTypeWithCommission::BUYCARD;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Sell", Qt::CaseInsensitive) == 0) {
        m_value = eOperationTypeWithCommission::SELL;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("BrokerCommission", Qt::CaseInsensitive) == 0) {
        m_value = eOperationTypeWithCommission::BROKERCOMMISSION;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("ExchangeCommission", Qt::CaseInsensitive) == 0) {
        m_value = eOperationTypeWithCommission::EXCHANGECOMMISSION;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("ServiceCommission", Qt::CaseInsensitive) == 0) {
        m_value = eOperationTypeWithCommission::SERVICECOMMISSION;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("MarginCommission", Qt::CaseInsensitive) == 0) {
        m_value = eOperationTypeWithCommission::MARGINCOMMISSION;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("OtherCommission", Qt::CaseInsensitive) == 0) {
        m_value = eOperationTypeWithCommission::OTHERCOMMISSION;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("PayIn", Qt::CaseInsensitive) == 0) {
        m_value = eOperationTypeWithCommission::PAYIN;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("PayOut", Qt::CaseInsensitive) == 0) {
        m_value = eOperationTypeWithCommission::PAYOUT;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Tax", Qt::CaseInsensitive) == 0) {
        m_value = eOperationTypeWithCommission::TAX;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("TaxLucre", Qt::CaseInsensitive) == 0) {
        m_value = eOperationTypeWithCommission::TAXLUCRE;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("TaxDividend", Qt::CaseInsensitive) == 0) {
        m_value = eOperationTypeWithCommission::TAXDIVIDEND;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("TaxCoupon", Qt::CaseInsensitive) == 0) {
        m_value = eOperationTypeWithCommission::TAXCOUPON;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("TaxBack", Qt::CaseInsensitive) == 0) {
        m_value = eOperationTypeWithCommission::TAXBACK;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Repayment", Qt::CaseInsensitive) == 0) {
        m_value = eOperationTypeWithCommission::REPAYMENT;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("PartRepayment", Qt::CaseInsensitive) == 0) {
        m_value = eOperationTypeWithCommission::PARTREPAYMENT;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Coupon", Qt::CaseInsensitive) == 0) {
        m_value = eOperationTypeWithCommission::COUPON;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Dividend", Qt::CaseInsensitive) == 0) {
        m_value = eOperationTypeWithCommission::DIVIDEND;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("SecurityIn", Qt::CaseInsensitive) == 0) {
        m_value = eOperationTypeWithCommission::SECURITYIN;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("SecurityOut", Qt::CaseInsensitive) == 0) {
        m_value = eOperationTypeWithCommission::SECURITYOUT;
        m_value_isSet = m_value_isValid = true;
    }
}

void OperationTypeWithCommission::fromJsonValue(QJsonValue json) {
fromJson(json.toString());
}

QString OperationTypeWithCommission::asJson() const {
    
    QString val;
    switch (m_value){
        case eOperationTypeWithCommission::BUY:
            val = "Buy";
            break;
        case eOperationTypeWithCommission::BUYCARD:
            val = "BuyCard";
            break;
        case eOperationTypeWithCommission::SELL:
            val = "Sell";
            break;
        case eOperationTypeWithCommission::BROKERCOMMISSION:
            val = "BrokerCommission";
            break;
        case eOperationTypeWithCommission::EXCHANGECOMMISSION:
            val = "ExchangeCommission";
            break;
        case eOperationTypeWithCommission::SERVICECOMMISSION:
            val = "ServiceCommission";
            break;
        case eOperationTypeWithCommission::MARGINCOMMISSION:
            val = "MarginCommission";
            break;
        case eOperationTypeWithCommission::OTHERCOMMISSION:
            val = "OtherCommission";
            break;
        case eOperationTypeWithCommission::PAYIN:
            val = "PayIn";
            break;
        case eOperationTypeWithCommission::PAYOUT:
            val = "PayOut";
            break;
        case eOperationTypeWithCommission::TAX:
            val = "Tax";
            break;
        case eOperationTypeWithCommission::TAXLUCRE:
            val = "TaxLucre";
            break;
        case eOperationTypeWithCommission::TAXDIVIDEND:
            val = "TaxDividend";
            break;
        case eOperationTypeWithCommission::TAXCOUPON:
            val = "TaxCoupon";
            break;
        case eOperationTypeWithCommission::TAXBACK:
            val = "TaxBack";
            break;
        case eOperationTypeWithCommission::REPAYMENT:
            val = "Repayment";
            break;
        case eOperationTypeWithCommission::PARTREPAYMENT:
            val = "PartRepayment";
            break;
        case eOperationTypeWithCommission::COUPON:
            val = "Coupon";
            break;
        case eOperationTypeWithCommission::DIVIDEND:
            val = "Dividend";
            break;
        case eOperationTypeWithCommission::SECURITYIN:
            val = "SecurityIn";
            break;
        case eOperationTypeWithCommission::SECURITYOUT:
            val = "SecurityOut";
            break;
        default:
            break;
    }
    return val;
}

QJsonValue OperationTypeWithCommission::asJsonValue() const {
    
    return QJsonValue(asJson());
}


OperationTypeWithCommission::eOperationTypeWithCommission OperationTypeWithCommission::getValue() const {
    return m_value;
}

void OperationTypeWithCommission::setValue(const OperationTypeWithCommission::eOperationTypeWithCommission& value){
    m_value = value;
    m_value_isSet = true;
}
bool OperationTypeWithCommission::isSet() const {
    
    return m_value_isSet;
}

bool OperationTypeWithCommission::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_value_isValid;
}

} // namespace OpenAPI
