/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OperationTrade.h
 *
 * 
 */

#ifndef OperationTrade_H
#define OperationTrade_H

#include <QJsonObject>

#include <QDateTime>
#include <QString>

#include "Enum.h"
#include "Object.h"

namespace OpenAPI {

class OperationTrade : public Object {
public:
    OperationTrade();
    OperationTrade(QString json);
    ~OperationTrade() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getTradeId() const;
    void setTradeId(const QString &trade_id);
    bool is_trade_id_Set() const;
    bool is_trade_id_Valid() const;

    QDateTime getDate() const;
    void setDate(const QDateTime &date);
    bool is_date_Set() const;
    bool is_date_Valid() const;

    double getPrice() const;
    void setPrice(const double &price);
    bool is_price_Set() const;
    bool is_price_Valid() const;

    qint32 getQuantity() const;
    void setQuantity(const qint32 &quantity);
    bool is_quantity_Set() const;
    bool is_quantity_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString trade_id;
    bool m_trade_id_isSet;
    bool m_trade_id_isValid;

    QDateTime date;
    bool m_date_isSet;
    bool m_date_isValid;

    double price;
    bool m_price_isSet;
    bool m_price_isValid;

    qint32 quantity;
    bool m_quantity_isSet;
    bool m_quantity_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OperationTrade)

#endif // OperationTrade_H
