/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Portfolio.h
 *
 * 
 */

#ifndef Portfolio_H
#define Portfolio_H

#include <QJsonObject>

#include "PortfolioPosition.h"
#include <QList>

#include "Enum.h"
#include "Object.h"

namespace OpenAPI {

class Portfolio : public Object {
public:
    Portfolio();
    Portfolio(QString json);
    ~Portfolio() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<PortfolioPosition> getPositions() const;
    void setPositions(const QList<PortfolioPosition> &positions);
    bool is_positions_Set() const;
    bool is_positions_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QList<PortfolioPosition> positions;
    bool m_positions_isSet;
    bool m_positions_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::Portfolio)

#endif // Portfolio_H
