/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "QTkfInvestOaMarketInstrumentList.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "QTkfInvestOaHelpers.h"

namespace OpenAPI {

QTkfInvestOaMarketInstrumentList::QTkfInvestOaMarketInstrumentList(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

QTkfInvestOaMarketInstrumentList::QTkfInvestOaMarketInstrumentList() {
    this->initializeModel();
}

QTkfInvestOaMarketInstrumentList::~QTkfInvestOaMarketInstrumentList() {}

void QTkfInvestOaMarketInstrumentList::initializeModel() {

    m_total_isSet = false;
    m_total_isValid = false;

    m_instruments_isSet = false;
    m_instruments_isValid = false;
}

void QTkfInvestOaMarketInstrumentList::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void QTkfInvestOaMarketInstrumentList::fromJsonObject(QJsonObject json) {

    m_total_isValid = ::OpenAPI::fromJsonValue(total, json[QString("total")]);
    m_total_isSet = !json[QString("total")].isNull() && m_total_isValid;

    m_instruments_isValid = ::OpenAPI::fromJsonValue(instruments, json[QString("instruments")]);
    m_instruments_isSet = !json[QString("instruments")].isNull() && m_instruments_isValid;
}

QString QTkfInvestOaMarketInstrumentList::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject QTkfInvestOaMarketInstrumentList::asJsonObject() const {
    QJsonObject obj;
    if (m_total_isSet) {
        obj.insert(QString("total"), ::OpenAPI::toJsonValue(total));
    }
    if (instruments.size() > 0) {
        obj.insert(QString("instruments"), ::OpenAPI::toJsonValue(instruments));
    }
    return obj;
}

double QTkfInvestOaMarketInstrumentList::getTotal() const {
    return total;
}
void QTkfInvestOaMarketInstrumentList::setTotal(const double &total) {
    this->total = total;
    this->m_total_isSet = true;
}

bool QTkfInvestOaMarketInstrumentList::is_total_Set() const{
    return m_total_isSet;
}

bool QTkfInvestOaMarketInstrumentList::is_total_Valid() const{
    return m_total_isValid;
}

QList<QTkfInvestOaMarketInstrument> QTkfInvestOaMarketInstrumentList::getInstruments() const {
    return instruments;
}
void QTkfInvestOaMarketInstrumentList::setInstruments(const QList<QTkfInvestOaMarketInstrument> &instruments) {
    this->instruments = instruments;
    this->m_instruments_isSet = true;
}

bool QTkfInvestOaMarketInstrumentList::is_instruments_Set() const{
    return m_instruments_isSet;
}

bool QTkfInvestOaMarketInstrumentList::is_instruments_Valid() const{
    return m_instruments_isValid;
}

bool QTkfInvestOaMarketInstrumentList::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_total_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (instruments.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool QTkfInvestOaMarketInstrumentList::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_total_isValid && m_instruments_isValid && true;
}

} // namespace OpenAPI
