/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * QTkfInvestOaCurrency.h
 *
 * 
 */

#ifndef QTkfInvestOaCurrency_H
#define QTkfInvestOaCurrency_H

#include <QJsonObject>


#include "QTkfInvestOaEnum.h"
#include "QTkfInvestOaObject.h"

namespace OpenAPI {

class QTkfInvestOaCurrency : public QTkfInvestOaEnum {
public:
    QTkfInvestOaCurrency();
    QTkfInvestOaCurrency(QString json);
    ~QTkfInvestOaCurrency() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    enum class eQTkfInvestOaCurrency {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        RUB, 
        USD, 
        EUR, 
        GBP, 
        HKD, 
        CHF, 
        JPY, 
        CNY, 
        TRY
    };
    QTkfInvestOaCurrency::eQTkfInvestOaCurrency getValue() const;
    void setValue(const QTkfInvestOaCurrency::eQTkfInvestOaCurrency& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    eQTkfInvestOaCurrency m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::QTkfInvestOaCurrency)

#endif // QTkfInvestOaCurrency_H
