/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * QTkfInvestOaCandles.h
 *
 * 
 */

#ifndef QTkfInvestOaCandles_H
#define QTkfInvestOaCandles_H

#include <QJsonObject>

#include "QTkfInvestOaCandle.h"
#include "QTkfInvestOaCandleResolution.h"
#include <QList>
#include <QString>

#include "QTkfInvestOaEnum.h"
#include "QTkfInvestOaObject.h"

namespace OpenAPI {

class QTkfInvestOaCandles : public QTkfInvestOaObject {
public:
    QTkfInvestOaCandles();
    QTkfInvestOaCandles(QString json);
    ~QTkfInvestOaCandles() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getFigi() const;
    void setFigi(const QString &figi);
    bool is_figi_Set() const;
    bool is_figi_Valid() const;

    QTkfInvestOaCandleResolution getInterval() const;
    void setInterval(const QTkfInvestOaCandleResolution &interval);
    bool is_interval_Set() const;
    bool is_interval_Valid() const;

    QList<QTkfInvestOaCandle> getCandles() const;
    void setCandles(const QList<QTkfInvestOaCandle> &candles);
    bool is_candles_Set() const;
    bool is_candles_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString figi;
    bool m_figi_isSet;
    bool m_figi_isValid;

    QTkfInvestOaCandleResolution interval;
    bool m_interval_isSet;
    bool m_interval_isValid;

    QList<QTkfInvestOaCandle> candles;
    bool m_candles_isSet;
    bool m_candles_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::QTkfInvestOaCandles)

#endif // QTkfInvestOaCandles_H
