/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * QTkfInvestOaSandboxAccount.h
 *
 * 
 */

#ifndef QTkfInvestOaSandboxAccount_H
#define QTkfInvestOaSandboxAccount_H

#include <QJsonObject>

#include "QTkfInvestOaBrokerAccountType.h"
#include <QString>

#include "QTkfInvestOaEnum.h"
#include "QTkfInvestOaObject.h"

namespace OpenAPI {

class QTkfInvestOaSandboxAccount : public QTkfInvestOaObject {
public:
    QTkfInvestOaSandboxAccount();
    QTkfInvestOaSandboxAccount(QString json);
    ~QTkfInvestOaSandboxAccount() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QTkfInvestOaBrokerAccountType getBrokerAccountType() const;
    void setBrokerAccountType(const QTkfInvestOaBrokerAccountType &broker_account_type);
    bool is_broker_account_type_Set() const;
    bool is_broker_account_type_Valid() const;

    QString getBrokerAccountId() const;
    void setBrokerAccountId(const QString &broker_account_id);
    bool is_broker_account_id_Set() const;
    bool is_broker_account_id_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QTkfInvestOaBrokerAccountType broker_account_type;
    bool m_broker_account_type_isSet;
    bool m_broker_account_type_isValid;

    QString broker_account_id;
    bool m_broker_account_id_isSet;
    bool m_broker_account_id_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::QTkfInvestOaSandboxAccount)

#endif // QTkfInvestOaSandboxAccount_H
