/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * QTkfInvestOaPortfolio.h
 *
 * 
 */

#ifndef QTkfInvestOaPortfolio_H
#define QTkfInvestOaPortfolio_H

#include <QJsonObject>

#include "QTkfInvestOaPortfolioPosition.h"
#include <QList>

#include "QTkfInvestOaEnum.h"
#include "QTkfInvestOaObject.h"

namespace OpenAPI {

class QTkfInvestOaPortfolio : public QTkfInvestOaObject {
public:
    QTkfInvestOaPortfolio();
    QTkfInvestOaPortfolio(QString json);
    ~QTkfInvestOaPortfolio() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<QTkfInvestOaPortfolioPosition> getPositions() const;
    void setPositions(const QList<QTkfInvestOaPortfolioPosition> &positions);
    bool is_positions_Set() const;
    bool is_positions_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QList<QTkfInvestOaPortfolioPosition> positions;
    bool m_positions_isSet;
    bool m_positions_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::QTkfInvestOaPortfolio)

#endif // QTkfInvestOaPortfolio_H
