/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "QTkfInvestOaInstrumentType.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "QTkfInvestOaHelpers.h"

namespace OpenAPI {

QTkfInvestOaInstrumentType::QTkfInvestOaInstrumentType(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

QTkfInvestOaInstrumentType::QTkfInvestOaInstrumentType() {
    this->initializeModel();
}

QTkfInvestOaInstrumentType::~QTkfInvestOaInstrumentType() {}

void QTkfInvestOaInstrumentType::initializeModel() {

    m_value_isSet = false;
    m_value_isValid = false;
    m_value = eQTkfInvestOaInstrumentType::INVALID_VALUE_OPENAPI_GENERATED;
}

void QTkfInvestOaInstrumentType::fromJson(QString jsonString) {
    
    if ( jsonString.compare("Stock", Qt::CaseInsensitive) == 0) {
        m_value = eQTkfInvestOaInstrumentType::STOCK;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Currency", Qt::CaseInsensitive) == 0) {
        m_value = eQTkfInvestOaInstrumentType::CURRENCY;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Bond", Qt::CaseInsensitive) == 0) {
        m_value = eQTkfInvestOaInstrumentType::BOND;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Etf", Qt::CaseInsensitive) == 0) {
        m_value = eQTkfInvestOaInstrumentType::ETF;
        m_value_isSet = m_value_isValid = true;
    }
}

void QTkfInvestOaInstrumentType::fromJsonValue(QJsonValue json) {
fromJson(json.toString());
}

QString QTkfInvestOaInstrumentType::asJson() const {
    
    QString val;
    switch (m_value){
        case eQTkfInvestOaInstrumentType::STOCK:
            val = "Stock";
            break;
        case eQTkfInvestOaInstrumentType::CURRENCY:
            val = "Currency";
            break;
        case eQTkfInvestOaInstrumentType::BOND:
            val = "Bond";
            break;
        case eQTkfInvestOaInstrumentType::ETF:
            val = "Etf";
            break;
        default:
            break;
    }
    return val;
}

QJsonValue QTkfInvestOaInstrumentType::asJsonValue() const {
    
    return QJsonValue(asJson());
}


QTkfInvestOaInstrumentType::eQTkfInvestOaInstrumentType QTkfInvestOaInstrumentType::getValue() const {
    return m_value;
}

void QTkfInvestOaInstrumentType::setValue(const QTkfInvestOaInstrumentType::eQTkfInvestOaInstrumentType& value){
    m_value = value;
    m_value_isSet = true;
}
bool QTkfInvestOaInstrumentType::isSet() const {
    
    return m_value_isSet;
}

bool QTkfInvestOaInstrumentType::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_value_isValid;
}

} // namespace OpenAPI
