/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * QTkfInvestOaInstrumentType.h
 *
 * 
 */

#ifndef QTkfInvestOaInstrumentType_H
#define QTkfInvestOaInstrumentType_H

#include <QJsonObject>


#include "QTkfInvestOaEnum.h"
#include "QTkfInvestOaObject.h"

namespace OpenAPI {

class QTkfInvestOaInstrumentType : public QTkfInvestOaEnum {
public:
    QTkfInvestOaInstrumentType();
    QTkfInvestOaInstrumentType(QString json);
    ~QTkfInvestOaInstrumentType() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    enum class eQTkfInvestOaInstrumentType {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        STOCK, 
        CURRENCY, 
        BOND, 
        ETF
    };
    QTkfInvestOaInstrumentType::eQTkfInvestOaInstrumentType getValue() const;
    void setValue(const QTkfInvestOaInstrumentType::eQTkfInvestOaInstrumentType& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    eQTkfInvestOaInstrumentType m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::QTkfInvestOaInstrumentType)

#endif // QTkfInvestOaInstrumentType_H
