/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "UserAccounts.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace OpenAPI {

UserAccounts::UserAccounts(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

UserAccounts::UserAccounts() {
    this->initializeModel();
}

UserAccounts::~UserAccounts() {}

void UserAccounts::initializeModel() {

    m_accounts_isSet = false;
    m_accounts_isValid = false;
}

void UserAccounts::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void UserAccounts::fromJsonObject(QJsonObject json) {

    m_accounts_isValid = ::OpenAPI::fromJsonValue(accounts, json[QString("accounts")]);
    m_accounts_isSet = !json[QString("accounts")].isNull() && m_accounts_isValid;
}

QString UserAccounts::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject UserAccounts::asJsonObject() const {
    QJsonObject obj;
    if (accounts.size() > 0) {
        obj.insert(QString("accounts"), ::OpenAPI::toJsonValue(accounts));
    }
    return obj;
}

QList<UserAccount> UserAccounts::getAccounts() const {
    return accounts;
}
void UserAccounts::setAccounts(const QList<UserAccount> &accounts) {
    this->accounts = accounts;
    this->m_accounts_isSet = true;
}

bool UserAccounts::is_accounts_Set() const{
    return m_accounts_isSet;
}

bool UserAccounts::is_accounts_Valid() const{
    return m_accounts_isValid;
}

bool UserAccounts::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (accounts.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool UserAccounts::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_accounts_isValid && true;
}

} // namespace OpenAPI
