/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "QTkfInvestOaSandboxApi.h"
#include "QTkfInvestOaHelpers.h"

#include <QJsonArray>
#include <QJsonDocument>

namespace OpenAPI {

QTkfInvestOaSandboxApi::QTkfInvestOaSandboxApi(const QString &scheme, const QString &host, int port, const QString &basePath, const int timeOut)
    : _scheme(scheme),
      _host(host),
      _port(port),
      _basePath(basePath),
      _timeOut(timeOut),
      isResponseCompressionEnabled(false),
      isRequestCompressionEnabled(false) {}

QTkfInvestOaSandboxApi::~QTkfInvestOaSandboxApi() {
}

void QTkfInvestOaSandboxApi::setScheme(const QString &scheme) {
    _scheme = scheme;
}

void QTkfInvestOaSandboxApi::setHost(const QString &host) {
    _host = host;
}

void QTkfInvestOaSandboxApi::setPort(int port) {
    _port = port;
}

void QTkfInvestOaSandboxApi::setBasePath(const QString &basePath) {
    _basePath = basePath;
}

void QTkfInvestOaSandboxApi::setTimeOut(const int timeOut) {
    _timeOut = timeOut;
}

void QTkfInvestOaSandboxApi::setWorkingDirectory(const QString &path) {
    _workingDirectory = path;
}

void QTkfInvestOaSandboxApi::addHeaders(const QString &key, const QString &value) {
    defaultHeaders.insert(key, value);
}

void QTkfInvestOaSandboxApi::enableRequestCompression() {
    isRequestCompressionEnabled = true;
}

void QTkfInvestOaSandboxApi::enableResponseCompression() {
    isResponseCompressionEnabled = true;
}

void QTkfInvestOaSandboxApi::abortRequests(){
    emit abortRequestsSignal();
}

void QTkfInvestOaSandboxApi::sandboxClearPost(const QString &broker_account_id) {
    QString fullPath = QString("%1://%2%3%4%5")
                           .arg(_scheme)
                           .arg(_host)
                           .arg(_port ? ":" + QString::number(_port) : "")
                           .arg(_basePath)
                           .arg("/sandbox/clear");

    if (fullPath.indexOf("?") > 0)
        fullPath.append("&");
    else
        fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("brokerAccountId")).append("=").append(QUrl::toPercentEncoding(::OpenAPI::toStringValue(broker_account_id)));

    QTkfInvestOaHttpRequestWorker *worker = new QTkfInvestOaHttpRequestWorker(this);
    worker->setTimeOut(_timeOut);
    worker->setWorkingDirectory(_workingDirectory);
    QTkfInvestOaHttpRequestInput input(fullPath, "POST");

    foreach (QString key, this->defaultHeaders.keys()) { input.headers.insert(key, this->defaultHeaders.value(key)); }

    connect(worker, &QTkfInvestOaHttpRequestWorker::on_execution_finished, this, &QTkfInvestOaSandboxApi::sandboxClearPostCallback);
    connect(this, &QTkfInvestOaSandboxApi::abortRequestsSignal, worker, &QObject::deleteLater); 
    worker->execute(&input);
}

void QTkfInvestOaSandboxApi::sandboxClearPostCallback(QTkfInvestOaHttpRequestWorker *worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    } else {
        msg = "Error: " + worker->error_str;
        error_str = QString("%1, %2").arg(worker->error_str).arg(QString(worker->response));
    }
    QTkfInvestOaEmpty output(QString(worker->response));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit sandboxClearPostSignal(output);
        emit sandboxClearPostSignalFull(worker, output);
    } else {
        emit sandboxClearPostSignalE(output, error_type, error_str);
        emit sandboxClearPostSignalEFull(worker, error_type, error_str);
    }
}

void QTkfInvestOaSandboxApi::sandboxCurrenciesBalancePost(const QTkfInvestOaSandboxSetCurrencyBalanceRequest &q_tkf_invest_oa_sandbox_set_currency_balance_request, const QString &broker_account_id) {
    QString fullPath = QString("%1://%2%3%4%5")
                           .arg(_scheme)
                           .arg(_host)
                           .arg(_port ? ":" + QString::number(_port) : "")
                           .arg(_basePath)
                           .arg("/sandbox/currencies/balance");

    if (fullPath.indexOf("?") > 0)
        fullPath.append("&");
    else
        fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("brokerAccountId")).append("=").append(QUrl::toPercentEncoding(::OpenAPI::toStringValue(broker_account_id)));

    QTkfInvestOaHttpRequestWorker *worker = new QTkfInvestOaHttpRequestWorker(this);
    worker->setTimeOut(_timeOut);
    worker->setWorkingDirectory(_workingDirectory);
    QTkfInvestOaHttpRequestInput input(fullPath, "POST");

    QString output = q_tkf_invest_oa_sandbox_set_currency_balance_request.asJson();
    input.request_body.append(output);

    foreach (QString key, this->defaultHeaders.keys()) { input.headers.insert(key, this->defaultHeaders.value(key)); }

    connect(worker, &QTkfInvestOaHttpRequestWorker::on_execution_finished, this, &QTkfInvestOaSandboxApi::sandboxCurrenciesBalancePostCallback);
    connect(this, &QTkfInvestOaSandboxApi::abortRequestsSignal, worker, &QObject::deleteLater); 
    worker->execute(&input);
}

void QTkfInvestOaSandboxApi::sandboxCurrenciesBalancePostCallback(QTkfInvestOaHttpRequestWorker *worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    } else {
        msg = "Error: " + worker->error_str;
        error_str = QString("%1, %2").arg(worker->error_str).arg(QString(worker->response));
    }
    QTkfInvestOaEmpty output(QString(worker->response));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit sandboxCurrenciesBalancePostSignal(output);
        emit sandboxCurrenciesBalancePostSignalFull(worker, output);
    } else {
        emit sandboxCurrenciesBalancePostSignalE(output, error_type, error_str);
        emit sandboxCurrenciesBalancePostSignalEFull(worker, error_type, error_str);
    }
}

void QTkfInvestOaSandboxApi::sandboxPositionsBalancePost(const QTkfInvestOaSandboxSetPositionBalanceRequest &q_tkf_invest_oa_sandbox_set_position_balance_request, const QString &broker_account_id) {
    QString fullPath = QString("%1://%2%3%4%5")
                           .arg(_scheme)
                           .arg(_host)
                           .arg(_port ? ":" + QString::number(_port) : "")
                           .arg(_basePath)
                           .arg("/sandbox/positions/balance");

    if (fullPath.indexOf("?") > 0)
        fullPath.append("&");
    else
        fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("brokerAccountId")).append("=").append(QUrl::toPercentEncoding(::OpenAPI::toStringValue(broker_account_id)));

    QTkfInvestOaHttpRequestWorker *worker = new QTkfInvestOaHttpRequestWorker(this);
    worker->setTimeOut(_timeOut);
    worker->setWorkingDirectory(_workingDirectory);
    QTkfInvestOaHttpRequestInput input(fullPath, "POST");

    QString output = q_tkf_invest_oa_sandbox_set_position_balance_request.asJson();
    input.request_body.append(output);

    foreach (QString key, this->defaultHeaders.keys()) { input.headers.insert(key, this->defaultHeaders.value(key)); }

    connect(worker, &QTkfInvestOaHttpRequestWorker::on_execution_finished, this, &QTkfInvestOaSandboxApi::sandboxPositionsBalancePostCallback);
    connect(this, &QTkfInvestOaSandboxApi::abortRequestsSignal, worker, &QObject::deleteLater); 
    worker->execute(&input);
}

void QTkfInvestOaSandboxApi::sandboxPositionsBalancePostCallback(QTkfInvestOaHttpRequestWorker *worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    } else {
        msg = "Error: " + worker->error_str;
        error_str = QString("%1, %2").arg(worker->error_str).arg(QString(worker->response));
    }
    QTkfInvestOaEmpty output(QString(worker->response));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit sandboxPositionsBalancePostSignal(output);
        emit sandboxPositionsBalancePostSignalFull(worker, output);
    } else {
        emit sandboxPositionsBalancePostSignalE(output, error_type, error_str);
        emit sandboxPositionsBalancePostSignalEFull(worker, error_type, error_str);
    }
}

void QTkfInvestOaSandboxApi::sandboxRegisterPost(const QTkfInvestOaSandboxRegisterRequest &q_tkf_invest_oa_sandbox_register_request) {
    QString fullPath = QString("%1://%2%3%4%5")
                           .arg(_scheme)
                           .arg(_host)
                           .arg(_port ? ":" + QString::number(_port) : "")
                           .arg(_basePath)
                           .arg("/sandbox/register");

    QTkfInvestOaHttpRequestWorker *worker = new QTkfInvestOaHttpRequestWorker(this);
    worker->setTimeOut(_timeOut);
    worker->setWorkingDirectory(_workingDirectory);
    QTkfInvestOaHttpRequestInput input(fullPath, "POST");

    QString output = q_tkf_invest_oa_sandbox_register_request.asJson();
    input.request_body.append(output);

    foreach (QString key, this->defaultHeaders.keys()) { input.headers.insert(key, this->defaultHeaders.value(key)); }

    connect(worker, &QTkfInvestOaHttpRequestWorker::on_execution_finished, this, &QTkfInvestOaSandboxApi::sandboxRegisterPostCallback);
    connect(this, &QTkfInvestOaSandboxApi::abortRequestsSignal, worker, &QObject::deleteLater); 
    worker->execute(&input);
}

void QTkfInvestOaSandboxApi::sandboxRegisterPostCallback(QTkfInvestOaHttpRequestWorker *worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    } else {
        msg = "Error: " + worker->error_str;
        error_str = QString("%1, %2").arg(worker->error_str).arg(QString(worker->response));
    }
    QTkfInvestOaSandboxRegisterResponse output(QString(worker->response));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit sandboxRegisterPostSignal(output);
        emit sandboxRegisterPostSignalFull(worker, output);
    } else {
        emit sandboxRegisterPostSignalE(output, error_type, error_str);
        emit sandboxRegisterPostSignalEFull(worker, error_type, error_str);
    }
}

void QTkfInvestOaSandboxApi::sandboxRemovePost(const QString &broker_account_id) {
    QString fullPath = QString("%1://%2%3%4%5")
                           .arg(_scheme)
                           .arg(_host)
                           .arg(_port ? ":" + QString::number(_port) : "")
                           .arg(_basePath)
                           .arg("/sandbox/remove");

    if (fullPath.indexOf("?") > 0)
        fullPath.append("&");
    else
        fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("brokerAccountId")).append("=").append(QUrl::toPercentEncoding(::OpenAPI::toStringValue(broker_account_id)));

    QTkfInvestOaHttpRequestWorker *worker = new QTkfInvestOaHttpRequestWorker(this);
    worker->setTimeOut(_timeOut);
    worker->setWorkingDirectory(_workingDirectory);
    QTkfInvestOaHttpRequestInput input(fullPath, "POST");

    foreach (QString key, this->defaultHeaders.keys()) { input.headers.insert(key, this->defaultHeaders.value(key)); }

    connect(worker, &QTkfInvestOaHttpRequestWorker::on_execution_finished, this, &QTkfInvestOaSandboxApi::sandboxRemovePostCallback);
    connect(this, &QTkfInvestOaSandboxApi::abortRequestsSignal, worker, &QObject::deleteLater); 
    worker->execute(&input);
}

void QTkfInvestOaSandboxApi::sandboxRemovePostCallback(QTkfInvestOaHttpRequestWorker *worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    } else {
        msg = "Error: " + worker->error_str;
        error_str = QString("%1, %2").arg(worker->error_str).arg(QString(worker->response));
    }
    QTkfInvestOaEmpty output(QString(worker->response));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit sandboxRemovePostSignal(output);
        emit sandboxRemovePostSignalFull(worker, output);
    } else {
        emit sandboxRemovePostSignalE(output, error_type, error_str);
        emit sandboxRemovePostSignalEFull(worker, error_type, error_str);
    }
}

} // namespace OpenAPI
