/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "QTkfInvestOaMarketOrderRequest.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "QTkfInvestOaHelpers.h"

namespace OpenAPI {

QTkfInvestOaMarketOrderRequest::QTkfInvestOaMarketOrderRequest(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

QTkfInvestOaMarketOrderRequest::QTkfInvestOaMarketOrderRequest() {
    this->initializeModel();
}

QTkfInvestOaMarketOrderRequest::~QTkfInvestOaMarketOrderRequest() {}

void QTkfInvestOaMarketOrderRequest::initializeModel() {

    m_lots_isSet = false;
    m_lots_isValid = false;

    m_operation_isSet = false;
    m_operation_isValid = false;
}

void QTkfInvestOaMarketOrderRequest::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void QTkfInvestOaMarketOrderRequest::fromJsonObject(QJsonObject json) {

    m_lots_isValid = ::OpenAPI::fromJsonValue(lots, json[QString("lots")]);
    m_lots_isSet = !json[QString("lots")].isNull() && m_lots_isValid;

    m_operation_isValid = ::OpenAPI::fromJsonValue(operation, json[QString("operation")]);
    m_operation_isSet = !json[QString("operation")].isNull() && m_operation_isValid;
}

QString QTkfInvestOaMarketOrderRequest::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject QTkfInvestOaMarketOrderRequest::asJsonObject() const {
    QJsonObject obj;
    if (m_lots_isSet) {
        obj.insert(QString("lots"), ::OpenAPI::toJsonValue(lots));
    }
    if (operation.isSet()) {
        obj.insert(QString("operation"), ::OpenAPI::toJsonValue(operation));
    }
    return obj;
}

qint32 QTkfInvestOaMarketOrderRequest::getLots() const {
    return lots;
}
void QTkfInvestOaMarketOrderRequest::setLots(const qint32 &lots) {
    this->lots = lots;
    this->m_lots_isSet = true;
}

bool QTkfInvestOaMarketOrderRequest::is_lots_Set() const{
    return m_lots_isSet;
}

bool QTkfInvestOaMarketOrderRequest::is_lots_Valid() const{
    return m_lots_isValid;
}

QTkfInvestOaOperationType QTkfInvestOaMarketOrderRequest::getOperation() const {
    return operation;
}
void QTkfInvestOaMarketOrderRequest::setOperation(const QTkfInvestOaOperationType &operation) {
    this->operation = operation;
    this->m_operation_isSet = true;
}

bool QTkfInvestOaMarketOrderRequest::is_operation_Set() const{
    return m_operation_isSet;
}

bool QTkfInvestOaMarketOrderRequest::is_operation_Valid() const{
    return m_operation_isValid;
}

bool QTkfInvestOaMarketOrderRequest::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_lots_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (operation.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool QTkfInvestOaMarketOrderRequest::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_lots_isValid && m_operation_isValid && true;
}

} // namespace OpenAPI
