/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "QTkfInvestOaOperationStatus.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "QTkfInvestOaHelpers.h"

namespace OpenAPI {

QTkfInvestOaOperationStatus::QTkfInvestOaOperationStatus(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

QTkfInvestOaOperationStatus::QTkfInvestOaOperationStatus() {
    this->initializeModel();
}

QTkfInvestOaOperationStatus::~QTkfInvestOaOperationStatus() {}

void QTkfInvestOaOperationStatus::initializeModel() {

    m_value_isSet = false;
    m_value_isValid = false;
    m_value = eQTkfInvestOaOperationStatus::INVALID_VALUE_OPENAPI_GENERATED;
}

void QTkfInvestOaOperationStatus::fromJson(QString jsonString) {
    
    if ( jsonString.compare("Done", Qt::CaseInsensitive) == 0) {
        m_value = eQTkfInvestOaOperationStatus::DONE;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Decline", Qt::CaseInsensitive) == 0) {
        m_value = eQTkfInvestOaOperationStatus::DECLINE;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Progress", Qt::CaseInsensitive) == 0) {
        m_value = eQTkfInvestOaOperationStatus::PROGRESS;
        m_value_isSet = m_value_isValid = true;
    }
}

void QTkfInvestOaOperationStatus::fromJsonValue(QJsonValue json) {
fromJson(json.toString());
}

QString QTkfInvestOaOperationStatus::asJson() const {
    
    QString val;
    switch (m_value){
        case eQTkfInvestOaOperationStatus::DONE:
            val = "Done";
            break;
        case eQTkfInvestOaOperationStatus::DECLINE:
            val = "Decline";
            break;
        case eQTkfInvestOaOperationStatus::PROGRESS:
            val = "Progress";
            break;
        default:
            break;
    }
    return val;
}

QJsonValue QTkfInvestOaOperationStatus::asJsonValue() const {
    
    return QJsonValue(asJson());
}


QTkfInvestOaOperationStatus::eQTkfInvestOaOperationStatus QTkfInvestOaOperationStatus::getValue() const {
    return m_value;
}

void QTkfInvestOaOperationStatus::setValue(const QTkfInvestOaOperationStatus::eQTkfInvestOaOperationStatus& value){
    m_value = value;
    m_value_isSet = true;
}
bool QTkfInvestOaOperationStatus::isSet() const {
    
    return m_value_isSet;
}

bool QTkfInvestOaOperationStatus::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_value_isValid;
}

} // namespace OpenAPI
