/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * QTkfInvestOaOrderType.h
 *
 * Тип заявки
 */

#ifndef QTkfInvestOaOrderType_H
#define QTkfInvestOaOrderType_H

#include <QJsonObject>


#include "QTkfInvestOaEnum.h"
#include "QTkfInvestOaObject.h"

namespace OpenAPI {

class QTkfInvestOaOrderType : public QTkfInvestOaEnum {
public:
    QTkfInvestOaOrderType();
    QTkfInvestOaOrderType(QString json);
    ~QTkfInvestOaOrderType() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    enum class eQTkfInvestOaOrderType {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        LIMIT, 
        MARKET
    };
    QTkfInvestOaOrderType::eQTkfInvestOaOrderType getValue() const;
    void setValue(const QTkfInvestOaOrderType::eQTkfInvestOaOrderType& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    eQTkfInvestOaOrderType m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::QTkfInvestOaOrderType)

#endif // QTkfInvestOaOrderType_H
