/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * QTkfInvestOaSandboxSetPositionBalanceRequest.h
 *
 * 
 */

#ifndef QTkfInvestOaSandboxSetPositionBalanceRequest_H
#define QTkfInvestOaSandboxSetPositionBalanceRequest_H

#include <QJsonObject>

#include <QString>

#include "QTkfInvestOaEnum.h"
#include "QTkfInvestOaObject.h"

namespace OpenAPI {

class QTkfInvestOaSandboxSetPositionBalanceRequest : public QTkfInvestOaObject {
public:
    QTkfInvestOaSandboxSetPositionBalanceRequest();
    QTkfInvestOaSandboxSetPositionBalanceRequest(QString json);
    ~QTkfInvestOaSandboxSetPositionBalanceRequest() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getFigi() const;
    void setFigi(const QString &figi);
    bool is_figi_Set() const;
    bool is_figi_Valid() const;

    double getBalance() const;
    void setBalance(const double &balance);
    bool is_balance_Set() const;
    bool is_balance_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString figi;
    bool m_figi_isSet;
    bool m_figi_isValid;

    double balance;
    bool m_balance_isSet;
    bool m_balance_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::QTkfInvestOaSandboxSetPositionBalanceRequest)

#endif // QTkfInvestOaSandboxSetPositionBalanceRequest_H
