/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Based on http://www.creativepulse.gr/en/blog/2014/restful-api-requests-using-qt-cpp-for-linux-mac-osx-ms-windows
 * By Alex Stylianos
 *
 **/

#ifndef QTkfInvestOa_HTTPREQUESTWORKER_H
#define QTkfInvestOa_HTTPREQUESTWORKER_H

#include <QMap>
#include <QNetworkAccessManager>
#include <QNetworkReply>
#include <QObject>
#include <QString>
#include <QTimer>

#include "QTkfInvestOaHttpFileElement.h"

namespace OpenAPI {

enum QTkfInvestOaHttpRequestVarLayout {
    NOT_SET,
    ADDRESS,
    URL_ENCODED,
    MULTIPART
};

class QTkfInvestOaHttpRequestInput {

public:
    QString url_str;
    QString http_method;
    QTkfInvestOaHttpRequestVarLayout var_layout;
    QMap<QString, QString> vars;
    QMap<QString, QString> headers;
    QList<QTkfInvestOaHttpFileElement> files;
    QByteArray request_body;

    QTkfInvestOaHttpRequestInput();
    QTkfInvestOaHttpRequestInput(QString v_url_str, QString v_http_method);
    void initialize();
    void add_var(QString key, QString value);
    void add_file(QString variable_name, QString local_filename, QString request_filename, QString mime_type);
};

class QTkfInvestOaHttpRequestWorker : public QObject {
    Q_OBJECT

public:
    explicit QTkfInvestOaHttpRequestWorker(QObject *parent = nullptr);
    virtual ~QTkfInvestOaHttpRequestWorker();

    QByteArray response;
    QNetworkReply::NetworkError error_type;
    QString error_str;

    QMap<QString, QString> getResponseHeaders() const;
    QString http_attribute_encode(QString attribute_name, QString input);
    void execute(QTkfInvestOaHttpRequestInput *input);
    static QSslConfiguration *sslDefaultConfiguration;
    void setTimeOut(int timeOutMs);
    void setWorkingDirectory(const QString &path);
    QTkfInvestOaHttpFileElement getHttpFileElement(const QString &fieldname = QString());
    QByteArray *getMultiPartField(const QString &fieldname = QString());
    void setResponseCompressionEnabled(bool enable);
    void setRequestCompressionEnabled(bool enable);
    int  getHttpResponseCode() const;

signals:
    void on_execution_finished(QTkfInvestOaHttpRequestWorker *worker);

private:
    enum QTkfInvestOaCompressionType{
        Zlib,
        Gzip
    };
    QNetworkAccessManager *manager;
    QMap<QString, QString> headers;
    QMap<QString, QTkfInvestOaHttpFileElement> files;
    QMap<QString, QByteArray *> multiPartFields;
    QString workingDirectory;
    QTimer timeOutTimer;
    bool isResponseCompressionEnabled;
    bool isRequestCompressionEnabled;
    int  httpResponseCode;

    void on_manager_timeout(QNetworkReply *reply);
    void process_response(QNetworkReply *reply);
    QByteArray decompress(const QByteArray& data);
    QByteArray compress(const QByteArray& input, int level, QTkfInvestOaCompressionType compressType);
 
private slots:
    void on_manager_finished(QNetworkReply *reply);
};

} // namespace OpenAPI

#endif // QTkfInvestOa_HTTPREQUESTWORKER_H
