/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * QTkfInvestOaOperationStatus.h
 *
 * Статус заявки
 */

#ifndef QTkfInvestOaOperationStatus_H
#define QTkfInvestOaOperationStatus_H

#include <QJsonObject>


#include "QTkfInvestOaEnum.h"
#include "QTkfInvestOaObject.h"

namespace OpenAPI {

class QTkfInvestOaOperationStatus : public QTkfInvestOaEnum {
public:
    QTkfInvestOaOperationStatus();
    QTkfInvestOaOperationStatus(QString json);
    ~QTkfInvestOaOperationStatus() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    enum class eQTkfInvestOaOperationStatus {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        DONE, 
        DECLINE, 
        PROGRESS
    };
    QTkfInvestOaOperationStatus::eQTkfInvestOaOperationStatus getValue() const;
    void setValue(const QTkfInvestOaOperationStatus::eQTkfInvestOaOperationStatus& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    eQTkfInvestOaOperationStatus m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::QTkfInvestOaOperationStatus)

#endif // QTkfInvestOaOperationStatus_H
