/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Candle.h
 *
 * 
 */

#ifndef Candle_H
#define Candle_H

#include <QJsonObject>

#include "CandleResolution.h"
#include <QDateTime>
#include <QString>

#include "Enum.h"
#include "Object.h"

#include "../../marty_decimal.h"


namespace OpenAPI {

class Candle : public Object {
public:
    Candle();
    Candle(QString json);
    ~Candle() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getFigi() const;
    void setFigi(const QString &figi);
    bool is_figi_Set() const;
    bool is_figi_Valid() const;

    CandleResolution getInterval() const;
    void setInterval(const CandleResolution &interval);
    bool is_interval_Set() const;
    bool is_interval_Valid() const;

    marty::Decimal getO() const;
    void setO(const marty::Decimal &o);
    bool is_o_Set() const;
    bool is_o_Valid() const;

    marty::Decimal getC() const;
    void setC(const marty::Decimal &c);
    bool is_c_Set() const;
    bool is_c_Valid() const;

    marty::Decimal getH() const;
    void setH(const marty::Decimal &h);
    bool is_h_Set() const;
    bool is_h_Valid() const;

    marty::Decimal getL() const;
    void setL(const marty::Decimal &l);
    bool is_l_Set() const;
    bool is_l_Valid() const;

    qint32 getV() const;
    void setV(const qint32 &v);
    bool is_v_Set() const;
    bool is_v_Valid() const;

    QDateTime getTime() const;
    void setTime(const QDateTime &time);
    bool is_time_Set() const;
    bool is_time_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString figi;
    bool m_figi_isSet;
    bool m_figi_isValid;

    CandleResolution interval;
    bool m_interval_isSet;
    bool m_interval_isValid;

    marty::Decimal o;
    bool m_o_isSet;
    bool m_o_isValid;

    marty::Decimal c;
    bool m_c_isSet;
    bool m_c_isValid;

    marty::Decimal h;
    bool m_h_isSet;
    bool m_h_isValid;

    marty::Decimal l;
    bool m_l_isSet;
    bool m_l_isValid;

    qint32 v;
    bool m_v_isSet;
    bool m_v_isValid;

    QDateTime time;
    bool m_time_isSet;
    bool m_time_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::Candle)

#endif // Candle_H
