/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "CurrencyPosition.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace OpenAPI {

CurrencyPosition::CurrencyPosition(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

CurrencyPosition::CurrencyPosition() {
    this->initializeModel();
}

CurrencyPosition::~CurrencyPosition() {}

void CurrencyPosition::initializeModel() {

    m_currency_isSet = false;
    m_currency_isValid = false;

    m_balance_isSet = false;
    m_balance_isValid = false;

    m_blocked_isSet = false;
    m_blocked_isValid = false;
}

void CurrencyPosition::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void CurrencyPosition::fromJsonObject(QJsonObject json) {

    m_currency_isValid = ::OpenAPI::fromJsonValue(currency, json[QString("currency")]);
    m_currency_isSet = !json[QString("currency")].isNull() && m_currency_isValid;

    m_balance_isValid = ::OpenAPI::fromJsonValue(balance, json[QString("balance")]);
    m_balance_isSet = !json[QString("balance")].isNull() && m_balance_isValid;

    m_blocked_isValid = ::OpenAPI::fromJsonValue(blocked, json[QString("blocked")]);
    m_blocked_isSet = !json[QString("blocked")].isNull() && m_blocked_isValid;
}

QString CurrencyPosition::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject CurrencyPosition::asJsonObject() const {
    QJsonObject obj;
    if (currency.isSet()) {
        obj.insert(QString("currency"), ::OpenAPI::toJsonValue(currency));
    }
    if (m_balance_isSet) {
        obj.insert(QString("balance"), ::OpenAPI::toJsonValue(balance));
    }
    if (m_blocked_isSet) {
        obj.insert(QString("blocked"), ::OpenAPI::toJsonValue(blocked));
    }
    return obj;
}

Currency CurrencyPosition::getCurrency() const {
    return currency;
}
void CurrencyPosition::setCurrency(const Currency &currency) {
    this->currency = currency;
    this->m_currency_isSet = true;
}

bool CurrencyPosition::is_currency_Set() const{
    return m_currency_isSet;
}

bool CurrencyPosition::is_currency_Valid() const{
    return m_currency_isValid;
}

marty::Decimal CurrencyPosition::getBalance() const {
    return balance;
}
void CurrencyPosition::setBalance(const marty::Decimal &balance) {
    this->balance = balance;
    this->m_balance_isSet = true;
}

bool CurrencyPosition::is_balance_Set() const{
    return m_balance_isSet;
}

bool CurrencyPosition::is_balance_Valid() const{
    return m_balance_isValid;
}

marty::Decimal CurrencyPosition::getBlocked() const {
    return blocked;
}
void CurrencyPosition::setBlocked(const marty::Decimal &blocked) {
    this->blocked = blocked;
    this->m_blocked_isSet = true;
}

bool CurrencyPosition::is_blocked_Set() const{
    return m_blocked_isSet;
}

bool CurrencyPosition::is_blocked_Valid() const{
    return m_blocked_isValid;
}

bool CurrencyPosition::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (currency.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_balance_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_blocked_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool CurrencyPosition::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_currency_isValid && m_balance_isValid && true;
}

} // namespace OpenAPI
