/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * LimitOrderRequest.h
 *
 * 
 */

#ifndef LimitOrderRequest_H
#define LimitOrderRequest_H

#include <QJsonObject>

#include "OperationType.h"

#include "Enum.h"
#include "Object.h"

#include "../../marty_decimal.h"


namespace OpenAPI {

class LimitOrderRequest : public Object {
public:
    LimitOrderRequest();
    LimitOrderRequest(QString json);
    ~LimitOrderRequest() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getLots() const;
    void setLots(const qint32 &lots);
    bool is_lots_Set() const;
    bool is_lots_Valid() const;

    OperationType getOperation() const;
    void setOperation(const OperationType &operation);
    bool is_operation_Set() const;
    bool is_operation_Valid() const;

    marty::Decimal getPrice() const;
    void setPrice(const marty::Decimal &price);
    bool is_price_Set() const;
    bool is_price_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 lots;
    bool m_lots_isSet;
    bool m_lots_isValid;

    OperationType operation;
    bool m_operation_isSet;
    bool m_operation_isValid;

    marty::Decimal price;
    bool m_price_isSet;
    bool m_price_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::LimitOrderRequest)

#endif // LimitOrderRequest_H
