/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Operations.h
 *
 * 
 */

#ifndef Operations_H
#define Operations_H

#include <QJsonObject>

#include "Operation.h"
#include <QList>

#include "Enum.h"
#include "Object.h"

namespace OpenAPI {

class Operations : public Object {
public:
    Operations();
    Operations(QString json);
    ~Operations() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<Operation> getOperations() const;
    void setOperations(const QList<Operation> &operations);
    bool is_operations_Set() const;
    bool is_operations_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QList<Operation> operations;
    bool m_operations_isSet;
    bool m_operations_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::Operations)

#endif // Operations_H
