/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "Operations.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace OpenAPI {

Operations::Operations(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

Operations::Operations() {
    this->initializeModel();
}

Operations::~Operations() {}

void Operations::initializeModel() {

    m_operations_isSet = false;
    m_operations_isValid = false;
}

void Operations::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void Operations::fromJsonObject(QJsonObject json) {

    m_operations_isValid = ::OpenAPI::fromJsonValue(operations, json[QString("operations")]);
    m_operations_isSet = !json[QString("operations")].isNull() && m_operations_isValid;
}

QString Operations::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject Operations::asJsonObject() const {
    QJsonObject obj;
    if (operations.size() > 0) {
        obj.insert(QString("operations"), ::OpenAPI::toJsonValue(operations));
    }
    return obj;
}

QList<Operation> Operations::getOperations() const {
    return operations;
}
void Operations::setOperations(const QList<Operation> &operations) {
    this->operations = operations;
    this->m_operations_isSet = true;
}

bool Operations::is_operations_Set() const{
    return m_operations_isSet;
}

bool Operations::is_operations_Valid() const{
    return m_operations_isValid;
}

bool Operations::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (operations.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool Operations::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_operations_isValid && true;
}

} // namespace OpenAPI
