/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef _OperationsApi_H
#define _OperationsApi_H

#include "HttpRequest.h"

#include "Error.h"
#include "OperationsResponse.h"
#include <QString>

#include <QObject>

namespace OpenAPI {

class OperationsApi : public QObject {
    Q_OBJECT

public:
    OperationsApi(const QString &scheme = "https", const QString &host = "api-invest.tinkoff.ru", int port = 0, const QString &basePath = "/openapi", const int timeOut = 0);
    ~OperationsApi();

    void setScheme(const QString &scheme);
    void setHost(const QString &host);
    void setPort(int port);
    void setBasePath(const QString &basePath);
    void setTimeOut(const int timeOut);
    void setWorkingDirectory(const QString &path);
    void addHeaders(const QString &key, const QString &value);
    void enableRequestCompression();
    void enableResponseCompression();
    void abortRequests();

    HttpRequestWorker* operationsGet(const QDateTime &from, const QDateTime &to, const QString &figi, const QString &broker_account_id);

private:
    QString _scheme, _host;
    int _port;
    QString _basePath;
    int _timeOut;
    QString _workingDirectory;
    QMap<QString, QString> defaultHeaders;
    bool isResponseCompressionEnabled;
    bool isRequestCompressionEnabled;

    void operationsGetCallback(HttpRequestWorker *worker);

signals:

    void operationsGetSignal(OperationsResponse summary);

    void operationsGetSignalFull(HttpRequestWorker *worker, OperationsResponse summary);

    void operationsGetSignalE(OperationsResponse summary, QNetworkReply::NetworkError error_type, QString error_str);

    void operationsGetSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);

    void abortRequestsSignal(); 
};

} // namespace OpenAPI
#endif
