/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "PortfolioApi.h"
#include "Helpers.h"

#include <QJsonArray>
#include <QJsonDocument>

namespace OpenAPI {

PortfolioApi::PortfolioApi(const QString &scheme, const QString &host, int port, const QString &basePath, const int timeOut)
    : _scheme(scheme),
      _host(host),
      _port(port),
      _basePath(basePath),
      _timeOut(timeOut),
      isResponseCompressionEnabled(false),
      isRequestCompressionEnabled(false) {}

PortfolioApi::~PortfolioApi() {
}

void PortfolioApi::setScheme(const QString &scheme) {
    _scheme = scheme;
}

void PortfolioApi::setHost(const QString &host) {
    _host = host;
}

void PortfolioApi::setPort(int port) {
    _port = port;
}

void PortfolioApi::setBasePath(const QString &basePath) {
    _basePath = basePath;
}

void PortfolioApi::setTimeOut(const int timeOut) {
    _timeOut = timeOut;
}

void PortfolioApi::setWorkingDirectory(const QString &path) {
    _workingDirectory = path;
}

void PortfolioApi::addHeaders(const QString &key, const QString &value) {
    defaultHeaders.insert(key, value);
}

void PortfolioApi::enableRequestCompression() {
    isRequestCompressionEnabled = true;
}

void PortfolioApi::enableResponseCompression() {
    isResponseCompressionEnabled = true;
}

void PortfolioApi::abortRequests(){
    emit abortRequestsSignal();
}

HttpRequestWorker* PortfolioApi::portfolioCurrenciesGet(const QString &broker_account_id) {
    QString fullPath = QString("%1://%2%3%4%5")
                           .arg(_scheme)
                           .arg(_host)
                           .arg(_port ? ":" + QString::number(_port) : "")
                           .arg(_basePath)
                           .arg("/portfolio/currencies");

    if (fullPath.indexOf("?") > 0)
        fullPath.append("&");
    else
        fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("brokerAccountId")).append("=").append(QUrl::toPercentEncoding(::OpenAPI::toStringValue(broker_account_id)));

    HttpRequestWorker *worker = new HttpRequestWorker(this);
    worker->setTimeOut(_timeOut);
    worker->setWorkingDirectory(_workingDirectory);
    HttpRequestInput input(fullPath, "GET");

    foreach (QString key, this->defaultHeaders.keys()) { input.headers.insert(key, this->defaultHeaders.value(key)); }

    connect(worker, &HttpRequestWorker::on_execution_finished, this, &PortfolioApi::portfolioCurrenciesGetCallback);
    connect(this, &PortfolioApi::abortRequestsSignal, worker, &QObject::deleteLater); 
    worker->execute(&input);

    return worker;
}

void PortfolioApi::portfolioCurrenciesGetCallback(HttpRequestWorker *worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    } else {
        msg = "Error: " + worker->error_str;
        error_str = QString("%1, %2").arg(worker->error_str).arg(QString(worker->response));
    }
    PortfolioCurrenciesResponse output(QString(worker->response));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit portfolioCurrenciesGetSignal(output);
        emit portfolioCurrenciesGetSignalFull(worker, output);
    } else {
        emit portfolioCurrenciesGetSignalE(output, error_type, error_str);
        emit portfolioCurrenciesGetSignalEFull(worker, error_type, error_str);
    }
}

HttpRequestWorker* PortfolioApi::portfolioGet(const QString &broker_account_id) {
    QString fullPath = QString("%1://%2%3%4%5")
                           .arg(_scheme)
                           .arg(_host)
                           .arg(_port ? ":" + QString::number(_port) : "")
                           .arg(_basePath)
                           .arg("/portfolio");

    if (fullPath.indexOf("?") > 0)
        fullPath.append("&");
    else
        fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("brokerAccountId")).append("=").append(QUrl::toPercentEncoding(::OpenAPI::toStringValue(broker_account_id)));

    HttpRequestWorker *worker = new HttpRequestWorker(this);
    worker->setTimeOut(_timeOut);
    worker->setWorkingDirectory(_workingDirectory);
    HttpRequestInput input(fullPath, "GET");

    foreach (QString key, this->defaultHeaders.keys()) { input.headers.insert(key, this->defaultHeaders.value(key)); }

    connect(worker, &HttpRequestWorker::on_execution_finished, this, &PortfolioApi::portfolioGetCallback);
    connect(this, &PortfolioApi::abortRequestsSignal, worker, &QObject::deleteLater); 
    worker->execute(&input);

    return worker;
}

void PortfolioApi::portfolioGetCallback(HttpRequestWorker *worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    } else {
        msg = "Error: " + worker->error_str;
        error_str = QString("%1, %2").arg(worker->error_str).arg(QString(worker->response));
    }
    PortfolioResponse output(QString(worker->response));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit portfolioGetSignal(output);
        emit portfolioGetSignalFull(worker, output);
    } else {
        emit portfolioGetSignalE(output, error_type, error_str);
        emit portfolioGetSignalEFull(worker, error_type, error_str);
    }
}

} // namespace OpenAPI
